using System;
using System.Collections.Generic;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using AirlineBookingSystem.Booking.Application.Commands;
using MediatR;
using AirlineBookingSystem.Bookings.Core.Repositories;
using MassTransit;
using AirlineBookingSystem.BuildingBlocks.Contracts.EventBus.Message;
namespace AirlineBookingSystem.Booking.Application.Handlers
{
    public class CreateBookingHandler : IRequestHandler<CreateBookingCommand, int>
    {
        private readonly IBookingRepository _bookingRepository;
        private readonly IPublishEndpoint _publishEndpoint;
        public CreateBookingHandler(IBookingRepository bookingRepository,IPublishEndpoint publishEndpoint)
        {
            _bookingRepository = bookingRepository;
            _publishEndpoint = publishEndpoint;

        }
        public async Task<int> Handle(CreateBookingCommand request, CancellationToken cancellationToken)
        {
            // Implementation goes here. For now, return a dummy value.
            var booking = new AirlineBookingSystem.Bookings.Core.Entities.Booking
            {
                Id = new Random().Next(1, 1000), // This should be generated by the database in a real application
                FlightId = request.FlightId,
                PassengerName = request.PassengerName,
                SeatNumber = request.SeatNumber,
                BookingDate = DateTime.UtcNow
            };
            await _bookingRepository.AddBookingsAsync(booking);
            // Publish the Flight Booked Event
            await _publishEndpoint.Publish(new FlightBookedEvent(
                
                    booking.Id,
                    booking.FlightId,
                    booking.PassengerName,
                    booking.SeatNumber,
                    booking.BookingDate
                ));
            return booking.Id;

        }
    }
}
