<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>9df28002-d6a8-4cd1-a7da-bc03cd5954ce</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AirlineBookingSystem.Booking.Core\AirlineBookingSystem.Bookings.Core.csproj" />
    <ProjectReference Include="..\AirlineBookingSystem.Booking.Infrastructure\AirlineBookingSystem.Bookings.Infrastructure.csproj" />
  </ItemGroup>

</Project>
