<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.1.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.0" />
    <PackageReference Include="MediatR" Version="14.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AirlineBookingSystem.Notification.Application\AirlineBookingSystem.Notification.Application.csproj" />
    <ProjectReference Include="..\AirlineBookingSystem.Notification.Core\AirlineBookingSystem.Notification.Core.csproj" />
    <ProjectReference Include="..\AirlineBookingSystem.Notification.Infrastructure\AirlineBookingSystem.Notification.Infrastructure.csproj" />
    <ProjectReference Include="..\AirlineBookingSystem.Payment.Api\AirlineBookingSystem.Payment.Api.csproj" />
  </ItemGroup>

</Project>
