<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MassTransit" Version="9.1.0" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="9.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.2" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="7.0.0" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.1.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AirlineBookingSystem.BuildingBlocks\AirlineBookingSystem.BuildingBlocks.csproj" />
    <ProjectReference Include="..\AirlineBookingSystem.Payment.Application\AirlineBookingSystem.Payment.Application.csproj" />
    <ProjectReference Include="..\AirlineBookingSystem.Payment.Core\AirlineBookingSystem.Payment.Core.csproj" />
    <ProjectReference Include="..\AirlineBookingSystem.Payment.Infrastructure\AirlineBookingSystem.Payment.Infrastructure.csproj" />
  </ItemGroup>

</Project>
